ALTER TABLE Books
ADD IsHidden BIT NOT NULL CONSTRAINT DF_Books_IsHidden DEFAULT 0;

ALTER TABLE Books
ADD IsFeatured BIT NOT NULL CONSTRAINT DF_Books_IsFeatured DEFAULT 0;

ALTER TABLE Books
ADD FeaturedRank INT NULL;
